# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_INPUT_ZEUS_EAR_KEY)	+= zeus_earkey.o
# SIO Switch Driver
obj-$(CONFIG_SWITCH_SIO)	+= switch_sio.o

