##
# Copyright (C) 2010, Samsung Electronics Co., Ltd. All Rights Reserved.
#  Written by System S/W Group, Open OS S/W R&D Team,
#  Mobile Communication Division.
##

##
# Project Name : Samsung Private Third-Party Device Drivers
#
# Project Description :
#
# Comments : tabstop = 8, shiftwidth = 8, noexpandtab
##

##
# File Name : Makefile
#
# File Description :
#
# Author : Joo, Young Jin (#4349, youngjin79.joo@samsung.com)
# Dept : System S/W Group (Open OS S/W R&D Team)
# Created Date : 09-Jul-2010
# Version : Baby-Raccoon
##

obj-$(CONFIG_TINY_FSR)		+= rfs_fsr/drivers/tfsr/
