##
# Copyright (C) 2010, Samsung Electronics Co., Ltd. All Rights Reserved.
#  Written by System S/W Group, Open OS S/W R&D Team,
#  Mobile Communication Division.
##

##
# Project Name : Samsung Private Third-Party Device Drivers
#
# Project Description :
#
# Comments : tabstop = 8, shiftwidth = 8, noexpandtab
##

##
# File Name : Makefile
#
# File Description :
#
# Author : Joo, Young Jin (#4349, youngjin79.joo@samsung.com)
# Dept : System S/W Group (Open OS S/W R&D Team)
# Created Date : 09-Jul-2010
# Version : Baby-Raccoon
##

#obj-$(CONFIG_TINY_FSR)			+= rfs_fsr/drivers/tfsr/
#obj-$(CONFIG_SAMSUNG_BATTERY)		+= battery/
#obj-$(CONFIG_SAMSUNG_VIBETONZ)		+= vibetonz/
#obj-$(CONFIG_SAMSUNG_DPRAM_FLASHLESS)	+= dpram_flashless/
#obj-$(CONFIG_INPUT_AK8973B)		+= ak8973b/
#obj-$(CONFIG_SAMSUNG_PROXIMITY_LIGHT)	+= PL_sensor/
#obj-$(CONFIG_INPUT_KXSD9)		+= kxsd9/
#obj-$(CONFIG_SAMSUNG_MULTIPDP)		+= multipdp/
#obj-$(CONFIG_SAMSUNG_SETPRIO)		+= setprio/
