#
# Makefile for the linux kernel.
#

# Common support
obj-y := id.o io.o control.o mux.o devices.o serial.o gpmc.o dmtimers.o \
	 timer-gp.o omap_hwmod.o omap_hwmod_common_data.o gpio.o

omap-2-3-common				= irq.o sdrc.o
omap-3-4-common				= dpll.o
prcm-common				= prcm.o powerdomain.o
clock-common				= clock.o clock_common_data.o clockdomain.o

obj-$(CONFIG_ARCH_OMAP2) += $(omap-2-3-common) $(prcm-common) $(clock-common)
obj-$(CONFIG_ARCH_OMAP3) += $(omap-2-3-common) $(prcm-common) $(clock-common) \
			    $(omap-3-4-common)
obj-$(CONFIG_ARCH_OMAP4) += $(omap-3-4-common) $(prcm-common) $(clock-common)

obj-$(CONFIG_OMAP_MCBSP) += mcbsp.o

# SMP support ONLY available for OMAP4
obj-$(CONFIG_SMP)			+= omap-smp.o omap-headsmp.o
obj-$(CONFIG_LOCAL_TIMERS)		+= timer-mpu.o
obj-$(CONFIG_HOTPLUG_CPU)		+= omap-hotplug.o
obj-$(CONFIG_ARCH_OMAP4)		+= omap44xx-smc.o

AFLAGS_omap44xx-smc.o		:=-Wa,-march=armv7-a

# Functions loaded to SRAM
obj-$(CONFIG_ARCH_OMAP2420)		+= sram242x.o
obj-$(CONFIG_ARCH_OMAP2430)		+= sram243x.o
obj-$(CONFIG_ARCH_OMAP3)		+= sram34xx.o

# Pin multiplexing
obj-$(CONFIG_ARCH_OMAP3)		+= mux34xx.o

# SMS/SDRC
obj-$(CONFIG_ARCH_OMAP2)		+= sdrc2xxx.o
# obj-$(CONFIG_ARCH_OMAP3)		+= sdrc3xxx.o

# Power Management
ifeq ($(CONFIG_PM),y)
obj-$(CONFIG_ARCH_OMAP2)		+= pm24xx.o
obj-$(CONFIG_ARCH_OMAP24XX)		+= sleep24xx.o
obj-$(CONFIG_ARCH_OMAP3)		+= pm.o pm34xx.o sleep34xx.o cpuidle34xx.o
obj-$(CONFIG_PM_DEBUG)			+= pm-debug.o
obj-$(CONFIG_OMAP_SMARTREFLEX)		+= smartreflex.o
endif

# PRCM
obj-$(CONFIG_ARCH_OMAP2)		+= cm.o
obj-$(CONFIG_ARCH_OMAP3)		+= cm.o
obj-$(CONFIG_ARCH_OMAP4)		+= cm4xxx.o voltage.o opp4xxx.o cpuidle44xx.o pm44xx.o

obj-$(CONFIG_OMAP_PM_SRF)		+=  resource34xx.o
# Clock framework
obj-$(CONFIG_ARCH_OMAP2)		+= clock2xxx.o clock2xxx_data.o
obj-$(CONFIG_ARCH_OMAP2420)		+= opp2420_data.o
obj-$(CONFIG_ARCH_OMAP3)		+= clock34xx.o clock34xx_data.o
obj-$(CONFIG_ARCH_OMAP2430)		+= opp2430_data.o
obj-$(CONFIG_ARCH_OMAP4)		+= clock44xx.o clock44xx_data.o

# EMU peripherals
obj-$(CONFIG_OMAP3_EMU)		+= emu.o

obj-$(CONFIG_OMAP_MBOX_FWK)		+= mailbox_mach.o
mailbox_mach-objs			:= mailbox.o

iommu-y					+= iommu2.o
iommu-$(CONFIG_ARCH_OMAP3)		+= omap3-iommu.o
iommu-$(CONFIG_ARCH_OMAP4)              += omap4-iommu.o
obj-$(CONFIG_OMAP_IOMMU)		+= $(iommu-y)

i2c-omap-$(CONFIG_I2C_OMAP)		:= i2c.o
obj-y					+= $(i2c-omap-m) $(i2c-omap-y)
# Debobs
obj-$(CONFIG_OMAP3_DEBOBS)	+= debobs.o

ifneq ($(CONFIG_MPU_BRIDGE),)
obj-y                                  += dspbridge.o
endif

# Specific board support
obj-$(CONFIG_MACH_OMAP_GENERIC)		+= board-generic.o
obj-$(CONFIG_MACH_OMAP_H4)		+= board-h4.o
obj-$(CONFIG_MACH_OMAP_2430SDP)		+= board-2430sdp.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OMAP_APOLLON)		+= board-apollon.o
obj-$(CONFIG_MACH_OMAP3_BEAGLE)		+= board-omap3beagle.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OMAP_LDP)		+= board-ldp.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OVERO)		+= board-overo.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OMAP3EVM)		+= board-omap3evm.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OMAP3_PANDORA)	+= board-omap3pandora.o \
					   mmc-twl4030.o
#obj-$(CONFIG_MACH_OMAP_3430SDP)		+= board-archer-port.o \
#					   mmc-twl4030.o
obj-$(CONFIG_MACH_NOKIA_N8X0)		+= board-n8x0.o
obj-$(CONFIG_MACH_SHOLES)		+= board-sholes.o \
					   board-sholes-camera.o \
					   board-sholes-flash.o \
					   board-sholes-panel.o \
					   board-sholes-spi.o \
					   board-sholes-sensors.o \
					   board-sholes-hsmmc.o \
					   board-sholes-keypad.o \
					   board-sholes-wifi.o \
					   board-sholes-mmcprobe.o 

# usbnet temporarily disabled
#					   board-sholes-usbnet.o \

obj-$(CONFIG_MACH_NOKIA_RX51)		+= board-rx51.o \
					   board-rx51-sdram.o \
					   board-rx51-peripherals.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_OMAP_ZOOM)		+= board-zoom2.o \
					   board-zoom-peripherals.o \
					   board-zoom-flash.o \
					   board-zoom2-camera.o \
					   board-zoom-panel.o \
					   mmc-twl4030.o \
					   board-zoom-debugboard.o
obj-$(CONFIG_MACH_OMAP_ZOOM3)		+= board-zoom3.o \
					   board-zoom-flash.o \
					   board-zoom-peripherals.o \
					   board-zoom2-camera.o \
					   board-zoom-panel.o \
					   mmc-twl4030.o \
					   board-zoom-debugboard.o
obj-$(CONFIG_MACH_OMAP_3630SDP)		+= board-3630sdp.o \
					   board-zoom-peripherals.o \
					   board-zoom2-camera.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_CM_T35)		+= board-cm-t35.o \
					   mmc-twl4030.o
obj-$(CONFIG_MACH_IGEP0020)		+= board-igep0020.o \
					   mmc-twl4030.o
obj-$(CONFIG_MMC_EMBEDDED_SDIO)         += board-4430sdp-wifi.o

obj-$(CONFIG_MACH_OMAP_4430SDP)		+= board-4430sdp.o \
					   mmc-twl4030.o

obj-$(CONFIG_MACH_OMAP3517EVM)     += board-am3517evm.o


obj-$(CONFIG_MACH_SAMSUNG) 		+= omap3-gptimer12.o \
					   omap34xx-padext.o

ifeq ($(CONFIG_MACH_NOWPLUS),y)
obj-$(CONFIG_MACH_NOWPLUS)         += board-nowplus.o \
                                           mmc-twl4030.o

endif

ifeq ($(CONFIG_MACH_ARCHER),y)
obj-$(CONFIG_MACH_ARCHER)                 += board-archer-port.o \
                                           mmc-twl4030.o 
                                          #board-3430sdp-flash.o
endif

# Platform specific device init code
obj-y					+= usb-musb.o
obj-$(CONFIG_MACH_OMAP2_TUSB6010)	+= usb-tusb6010.o
ifneq ($(CONFIG_USB_EHCI_HCD),)
	obj-y				+= usb-ehci.o
endif


onenand-$(CONFIG_MTD_ONENAND_OMAP2)	:= gpmc-onenand.o
obj-y					+= $(onenand-m) $(onenand-y)

nand-$(CONFIG_MTD_NAND_OMAP2)		:= gpmc-nand.o
obj-y					+= $(nand-m) $(nand-y)

smc91x-$(CONFIG_SMC91X)			:= gpmc-smc91x.o
obj-y					+= $(smc91x-m) $(smc91x-y)
