

omap_ntfydisp = hw_mbox.o notify_dispatcher.o hw_ocp.o


obj-$(CONFIG_NOTIFY_DISPATCHER) += notify_disp.o
notify_disp-objs = $(omap_ntfydisp)


ccflags-y += -Wno-strict-prototypes

#Machine dependent
ccflags-y += -DCHNL_MESSAGES -DUSE_LEVEL_1_MACROS  \
                -DCONFIG_DISABLE_BRIDGE_PM -DDSP_TRACEBUF_DISABLED \
		-DVPOM4430_1_06

#Header files
ccflags-y += -Idrivers/dsp/syslink/inc

